[package]
name = "dkg-standalone-node"
version = "3.0.0"
description = "A fresh FRAME-based Substrate node, ready for hacking."
authors = ["Webb tools"]
homepage = "https://webb.tools/"
edition = "2021"
license = "Unlicense"
publish = false
repository = "https://github.com/webb-tools/dkg-substrate"
build = "build.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "dkg-standalone-node"

[dependencies]
structopt = "0.3.8"
rand = "0.7.2"

sc-cli = { git = 'https://github.com/paritytech/substrate', branch = 'master', features = ["wasmtime"] }
sp-core = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
sc-executor = { git = 'https://github.com/paritytech/substrate', branch = 'master', features = ["wasmtime"] }
sc-service = { git = 'https://github.com/paritytech/substrate', branch = 'master', features = ["wasmtime"] }
sc-telemetry = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
sc-keystore = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
sc-transaction-pool = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
sc-transaction-pool-api = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
sc-consensus-aura = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
sp-consensus-aura = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
sp-consensus = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
sc-consensus = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
sc-finality-grandpa = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
sp-finality-grandpa = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
sc-client-api = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
sp-runtime = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
sp-timestamp = { git = 'https://github.com/paritytech/substrate', branch = 'master' }

# These dependencies are used for the node template's RPCs
jsonrpc-core = "18.0.0"
sc-rpc = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
sp-api = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
sc-rpc-api = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
sp-blockchain = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
sp-block-builder = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
sc-basic-authorship = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
substrate-frame-rpc-system = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
pallet-transaction-payment-rpc = { git = 'https://github.com/paritytech/substrate', branch = 'master' }

# These dependencies are used for runtime benchmarking
frame-benchmarking = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
frame-benchmarking-cli = { git = 'https://github.com/paritytech/substrate', branch = 'master' }

# Local dependencies
dkg-gadget = { path = "../../dkg-gadget", default-features = false }

dkg-standalone-runtime = { version = "3.0.0", path = "../runtime" }

[dev-dependencies]
env_logger = "0.9"
futures = "0.3.16"
tempfile = "3.1.0"
assert_cmd = "2.0.2"
nix = "0.23"
serde_json = "1.0"
regex = "1"
platforms = "2.0"
async-std = { version = "1.10.0", features = ["attributes"] }
soketto = "0.4.2"
criterion = { version = "0.3.5", features = [ "async_tokio" ] }
tokio = { version = "1.13", features = ["macros", "time"] }
jsonrpsee-ws-client = "0.4.1"
wait-timeout = "0.2"
remote-externalities = { git = 'https://github.com/paritytech/substrate', branch = 'master'}
pallet-timestamp = { git = 'https://github.com/paritytech/substrate', branch = 'master'}
node-primitives = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
substrate-api-client = { git = "https://github.com/scs/substrate-api-client", rev = "1a5951450203b11cb347d624891ba608e2e27f6d" }
codec = { package = "parity-scale-codec", version = "2.0.0", features = ["derive"] }
scale-info = { version = "1.0", features = ["derive"] }
hex = "0.4.3"
sp-keyring = { git = 'https://github.com/paritytech/substrate', branch = 'master' }
serde = { version = "1.0", features = ["derive"] }
ac-compose-macros = { git = "https://github.com/scs/substrate-api-client", rev = "1a5951450203b11cb347d624891ba608e2e27f6d"}
ac-primitives = { git = "https://github.com/scs/substrate-api-client", rev = "1a5951450203b11cb347d624891ba608e2e27f6d" }


[build-dependencies]
substrate-build-script-utils = { git = 'https://github.com/paritytech/substrate', branch = 'master' }

[features]
default = []
runtime-benchmarks = [
	"dkg-standalone-runtime/runtime-benchmarks",
]
